### ISSUE TITLE
Broken pipe (os error 32)

### ISSUE THREAD

**Issue by mel4tonin** [kpcyrd/spotify-launcher#43]
[melatonin@rockstar Downloads]$ spotify-launcher 
[2024-02-11T18:25:29Z INFO  spotify_launcher::config] Loading configuration file at "/etc/spotify-launcher.conf"
[2024-02-11T18:25:29Z INFO  spotify_launcher::apt] Downloading release file...
[2024-02-11T18:25:29Z INFO  spotify_launcher::apt] Downloading signature...
[2024-02-11T18:25:29Z INFO  spotify_launcher::apt] Verifying pgp signature...
[2024-02-11T18:25:29Z INFO  spotify_launcher::apt] Signature verified successfully!
[2024-02-11T18:25:29Z INFO  spotify_launcher::apt] Downloading package index...
[2024-02-11T18:25:29Z INFO  spotify_launcher::apt] Verifying with sha256sum hash...
[2024-02-11T18:25:29Z INFO  spotify_launcher::apt] Downloading deb file for "spotify-client_1.2.26.1187.g36b715a1_amd64.deb" version="spotify-client" ("1:1.2.26.1187.g36b715a1")
[2024-02-11T18:25:29Z INFO  spotify_launcher::apt] Retrying download...
This option is not available. Please see --help for all possible usages.
[2024-02-11T18:25:29Z WARN  spotify_launcher::apt] Download has failed: Broken pipe (os error 32)
[2024-02-11T18:25:29Z INFO  spotify_launcher::apt] Retrying download...
[2024-02-11T18:25:30Z WARN  spotify_launcher::apt] Download has failed: Broken pipe (os error 32)
[2024-02-11T18:25:30Z INFO  spotify_launcher::apt] Retrying download...
[2024-02-11T18:25:30Z WARN  spotify_launcher::apt] Download has failed: Broken pipe (os error 32)
[2024-02-11T18:25:30Z INFO  spotify_launcher::apt] Retrying download...
[2024-02-11T18:25:30Z WARN  spotify_launcher::apt] Download has failed: Broken pipe (os error 32)
[2024-02-11T18:25:30Z INFO  spotify_launcher::apt] Retrying download...
[2024-02-11T18:25:30Z WARN  spotify_launcher::apt] Download has failed: Broken pipe (os error 32)
Error: Exceeded number of retries for download

How can i fix this?

**Comment by kpcyrd** [comment]
It seems zenity is installed but it doesn't recognize some of the flags.

You can try running this directly:

```
zenity --progress --title 'Downloading spotify' --text=Downloading... --no-cancel --ok-label 😺
```

I've tested this just now with `zenity 4.0.1` on Arch Linux. There's also a slight chance utf-8 is not configured correctly on your system.

spotify-launcher currently doesn't handle the progress indicator exiting unexpectedly.

**Comment by mel4tonin** [comment]
melatonin@rockstar ~> zenity --progress --title 'Downloading spotify' --text=Downloading... --no-cancel --ok-label 😺
This option is not available. Please see --help for all possible usages.

I think this isnt the problem, when i go to the http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.2.26.1187.g36b715a1_amd64.deb and try installing from here, i am still getting errors.
![image](https://github.com/kpcyrd/spotify-launcher/assets/110846681/87b92b1e-b0dc-4f24-89fc-6f8805b88ffa)

**Comment by kpcyrd** [comment]
Can you try to narrow down which flag is not working and share the zenity version (and/or operating system you're using)?

Failing downloads have been reported in #31 by multiple people, however spotify-launcher will automatically try to resume the download and only download what's still missing.

**Comment by mel4tonin** [comment]
I am using Arch linux now, i think i failed on my utf-8 configuration, i will try later.

**Comment by darktaiga01** [comment]
I just got this error, and I fixed it by setting my locale to UTF-8.

**Comment by Tyruxanj** [comment]
> Can you try to narrow down which flag is not working and share the `zenity --version` output (and/or operating system you're using)?

I am using arch with kde, it doesnt like the emoji in the --ok-label flag.

here is my zenity --version output
```
(zenity:17936): Gtk-WARNING **: 19:06:39.400: Locale not supported by C library.
	Using the fallback 'C' locale.
4.0.1
```

I have tried logging as root and regenerating the locales I use. No luck so far.
```
$ localedef --list-archive
en_US.utf8
tr_TR.utf8
```

**Comment by Bekert** [comment]
Same here. It broke after an update a few days ago

**Comment by kpcyrd** [comment]
@Bekert try running the command mentioned in https://github.com/kpcyrd/spotify-launcher/issues/43#issuecomment-1937837440

```sh
zenity --progress --title 'Downloading spotify' --text=Downloading... --no-cancel --ok-label 😺
```

if it doesn't work your system has broken locales, see also `locale -a` and https://wiki.archlinux.org/title/Locale

**Comment by Bekert** [comment]
Locale indeed was the problem. The issue not related to spotify-launcher, but I'll post it anyway in case someone finds it helpful

 `locale` was giving the following output

```
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=en_150.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I've solved the issue by explicitly setting LC_ALL (it overwrites all other LC_* variables) to en_US.UTF-8 in the enviroment

```
$ LC_ALL=en_US.UTF-8 spotify-launcher
```

I have no idea what's wrong with my locales and why it broke after an update, but that's it...

**Comment by kpcyrd** [comment]
The libc locale system is terrible unfortunately. :broken_heart: 

The output of `locale` looks identical for me:
```
% locale   
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

This error is very likely what's wrong on your system:
```
locale: Cannot set LC_ALL to default locale: No such file or directory
```

Try running as root:
```
locale-gen
```

You can also try running
```
strace -f locale
```
To check what it's trying to access immediately before printing the error.

**Comment by Julian-1-2-3-4-5** [comment]
i have the same problem as well am for now bypassing by setting LC_ALL to en_US.UTF-8

**Comment by shreyasc60** [comment]
> I just got this error, and I fixed it by setting my locale to UTF-8.

Thanks, I just fixed this issue doing the same :)

**Comment by iUnstable0** [comment]
this is still happening to me even with LC_ALL :(

**Comment by s0me0ther** [comment]
> this is still happening to me even with LC_ALL :(

Same for me.
Running on latest arch

locale output looks fine:
```
locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

The launcher can't download:
```
LC_ALL=en_US.UTF-8 spotify-launcher
[2024-10-08T05:40:36Z INFO  spotify_launcher::config] Loading configuration file at "/etc/spotify-launcher.conf"
[2024-10-08T05:40:36Z INFO  spotify_launcher::apt] Downloading release file...
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Downloading signature...
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Verifying pgp signature...
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Signature verified successfully!
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Downloading package index...
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Verifying with sha256sum hash...
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Downloading deb file for "spotify-client_1.2.47.364.gf06e5cee_amd64.deb" version="spotify-client" ("1:1.2.47.364.gf06e5cee")
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Retrying download...
[2024-10-08T05:40:37Z WARN  spotify_launcher::apt] Download has failed: Broken pipe (os error 32)
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Retrying download...
[2024-10-08T05:40:37Z WARN  spotify_launcher::apt] Download has failed: Broken pipe (os error 32)
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Retrying download...
[2024-10-08T05:40:37Z WARN  spotify_launcher::apt] Download has failed: Broken pipe (os error 32)
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Retrying download...
[2024-10-08T05:40:37Z WARN  spotify_launcher::apt] Download has failed: Broken pipe (os error 32)
[2024-10-08T05:40:37Z INFO  spotify_launcher::apt] Retrying download...
[2024-10-08T05:40:37Z WARN  spotify_launcher::apt] Download has failed: Broken pipe (os error 32)
Error: Exceeded number of retries for download
```

Any toughts?

**Comment by Slaviro** [comment]
I also did try some locale-related fixes, they didn't work for me either. 

In my case the error appeared to be some kind of incompatibility with Wayland. 

I saw the following error from Zenity "Error 71 (Protocol error) dispatching to Wayland display"  and switching to Xorg did solve the problem for a time.

**Comment by alamb3142** [comment]
I had this yesterday. My locale settings were all fine. I did an update of spotify-launcher and then the whole system, which didn't fix it, but it was working again after a reboot.

**Comment by anp369** [comment]
I use arch with KDE and had the same problem.
Since the zenity thing apparently uses some GTK rendering, I found [this](https://bbs.archlinux.org/viewtopic.php?id=299488)  fix.

Append `GSK_RENDERER=ngl` to `/etc/environment` and reboot. That fixed the dialog and also the downloading for me

**Comment by fateers** [comment]
Had the same issue, just had to configure locale (uncomment in /etc/locale.gen and run locale-gen), as I forgot to do so while installing Arch.
